name: Update knowledge base

permissions:
  contents: write             # push‑recht voor commit

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ← doorgeven aan script
        run: node scripts/updateKnowledge.js

      - uses: EndBug/add-and-commit@v9
        if: success()
        with:
          add: '.'
          default_author: github_actions
          message: "chore: auto‑refresh node‑list"
